### ISSUE TITLE
Fails For Bigger Channel

### ISSUE THREAD

**Issue by telegrambotting** [DiyRex/Youtube-To-G-Drive#1]
I tried your colab 
i see issue when i try to Archive bigger channel it simply stops after 100 Videos
![image](https://user-images.githubusercontent.com/93691661/140255405-51c7d9d6-b87f-405f-9e19-67e0d866cce4.png)

**Comment by telegrambotting** [comment]
and How to Archive Whole YouTube Channel with more than 900 Videos

**Comment by telegrambotting** [comment]
am i doing something wrong?

**Comment by DiyRex** [comment]
What is the resolution did you select? I think There is a lower resolution video in that collection

**Comment by telegrambotting** [comment]
1080p

**Comment by telegrambotting** [comment]
and one more problem is it shows  playlist finished 
when only 100 videos are archived

**Comment by DiyRex** [comment]
> 1080p

I see. There can be a 720P video somewhere when the script find that video isn't 1080p then the script stop. Give a try to download using 720p and check

**Comment by telegrambotting** [comment]
but it will download all videos in 720p
i dont like 720p
any help?

**Comment by telegrambotting** [comment]
What lines to add so it can automate variation in video quality and give the best possible?

**Comment by DiyRex** [comment]
Sure I will check it. 🙂❤️
